### ISSUE TITLE
1.0 release planning

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/rustix#753]
Here's a planning issue for a 1.0 release, similar to the one for the [0.38 release](https://github.com/bytecodealliance/rustix/issues/578). Hopefully we won't need a semver bump for a good long while, but when we do, here's the list of changes we can make:

 - [x] Remove the deprecated mount functions in the `fs` module [(details)](https://github.com/bytecodealliance/rustix/pull/752#issuecomment-1642328674)
 - [x] Make the underlying type of `rustix::fs::Access` consistent between linux_raw and libc backends (https://github.com/bytecodealliance/rustix/pull/1152)
 - [x] Rename `mount_recursive_bind` to `mount_bind_recursive`? https://github.com/bytecodealliance/rustix/pull/763#issuecomment-1662756184 (https://github.com/bytecodealliance/rustix/pull/1273)
 - [x] Change `SeekFrom::Hole` and `SeekFrom::Data`'s field from `i64` to `u64`. (https://github.com/bytecodealliance/rustix/pull/1266)
 - [x] rename `Shutdown::ReadWrite` to `Shutdown::Both` to align with std (https://github.com/bytecodealliance/rustix/pull/1264)
 - [x] remove the `features = ["extra_traits"]` from the libc dependency (#1168)
 - [x] move (or perhaps alias?) `sched_yield` and other `sched_*` functions from `process` to `thread`, since they apply to threads rather than processes on Linux etc. (https://github.com/bytecodealliance/rustix/pull/1265)
 - [x] `stx_mtime` and similar members of `Statx` should be `i64`, because Unix timestamps can be negative.
 - [x] `futex`'s first argument should be `Atomic`
 - [x] Remove `get_` from sockopt getters, following [Rust convention](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter). Consider removing `get_` in other things too. (https://github.com/bytecodealliance/rustix/pull/1269)
 - [x] The `udata` argument to `rustix::event::kqueue::Event::new` should be a pointer instead of an `isize` in order to better preserve provenance. (https://github.com/bytecodealliance/rustix/pull/1270)
 - [x] The `stx_attributes_mask` field of `Statx` with flags like `libc::STATX_ATTR_MOUNT_ROOT` should ideally be a bitflags, which requires making `Statx` a custom type (which should match layout with `libc::statx`). (https://github.com/bytecodealliance/rustix/pull/1282)
 - [x] Rename `get_*` functions (eg. sockopts) to remove the `get_` prefix, which is more idiomatic Rust?
 - [x] Rename `MountPropagationFlags::SLAVE` (#1169)
 - [x] Rename some of `WaitidOptions`, `WaitidStatus`, and/or `WaitId` to make the capitalization of `Id` consistent (https://github.com/bytecodealliance/rustix/pull/1267)
 - [x] Remove the `inotify_` prefixes from things in the `fs::inotify` module.
 - [x] Remove the `shm_` and `Shm` prefixes from things in the `shm` module.
 - [x] Figure out a way to do a `recv` into an uninitialized buffer with the `TRUNC` flag set (see #1159) (https://github.com/bytecodealliance/rustix/pull/1278)
 - [x] remove rustix::procfs and publish [rustix-linux-procfs](https://github.com/sunfishcode/rustix-linux-procfs) as the replacement (https://github.com/bytecodealliance/rustix/pull/1275)
 - [x] remove linux-raw-sys from the public API (#1152) (https://github.com/bytecodealliance/rustix/pull/1277) (https://github.com/bytecodealliance/rustix/pull/1282)
 - [x] change `io_uring_register_files_skip` from a `const fn` to a constant. (https://github.com/bytecodealliance/rustix/pull/1268)

Deferring for now:
 - move rustix::thread sleep functions into a new rustix::sleep module, because they're usable from single-threaded programs too
 - Move `Dir` into its own crate, and have rustix export `getdents` directly?
 - Split `open` and `openat` into separate functions for "create" which needs a mode vs. "open existing" which doesn't need a mode?
 - Make `RecvAncillaryBuffer::drain` always remove all messages, even if the iterator isn't exhausted. With that, we can remove the `read_and_length` in `AncillaryDrain`.
 - Replace `rustix::cstr!` with something like `rustix::nativestr!` so that users don't hard code "native strings are C strings" in their code?
 - rename `Arg::as_str` to avoid "a method with this name may be added to the standard library in the future" warnings
 - `rustix::process::waitpid` has no way to wait for specific process groups (`Pid` now requires non-negative values). `waitpgid` has been added as a temporary workaround.
 - remove libc from the public API (#1152) (https://github.com/bytecodealliance/rustix/pull/1277)

Don't do these:
 - `set_ip_add_membership`/`get_ip_add_membership` should take `address` and `ifindex` arguments and `*_with_ifindex` should be removed.
 - Rename `ClockId::Uptime` on FreeBSD to `Boottime`, since it's an alias

**Comment by notgull** [comment]
It would be nice to have an uninitialized buffer API for `read`, `recv`, `recvmsg`, etc. That way you could read to completely uninitialized buffers.

**Comment by sunfishcode** [comment]
Reading into uninitialized buffers is tracked in https://github.com/bytecodealliance/rustix/issues/81.

**Comment by sunfishcode** [comment]
I think it makes sense to call the next release 1.0, instead of 0.39.

0.x version numbers are sometimes seen as signifying instability. And, 0.x version numbers don't have an equivalent of minor versions.

The overall plan here can stay the same. 1.0 (formerly 0.39 here) would still be a good long while after 0.38, and a good long while after that would be a 2.0 (instead of a 0.40), and so on.

**Comment by notgull** [comment]
If this is going to be a stable release, we should make sure that `libc` and `linux-raw-sys` aren't exposed in the public API. I know there are still a few places where it is.

In my opinion a stable release is a bad idea, as the API is still somewhat volatile. There should at least be an "unstable" feature flag to test new APIs for inclusion, like Tokio has.

**Comment by sunfishcode** [comment]
I already consider 0.38 to be stable. For example, I maintain an older version of linux-raw-sys to preserve compatibility with rustix 0.38. And I'm not aware of any significant volatility in the 0.38 API. It's added lots of features, and even deprecated a handful of things, but ideas for breaking changes are collected here in this issue, specifically to keep 0.38 stable.

So my idea for 1.0 is just to better communicate what's already happening.

It would be nice to better encapsulate libc/linux-raw-sys types, and I'm open to adding an "unstable" feature flag if there's a need for it. I'm under the impression that these aren't urgent right now, though I'd be happy to learn more about how these impact users.

**Comment by SUPERCILEX** [comment]
`rustix::cstr!` should be removed now that c strings just went stable: https://github.com/rust-lang/rust/pull/117472

**Comment by sunfishcode** [comment]
Rustix's MSRV won't support new features like `c"..."` strings for quite some time, so we'll need to keep `cstr!` for now.

**Comment by SUPERCILEX** [comment]
I'd like to propose making the `timeout` param in https://docs.rs/rustix/latest/rustix/event/fn.poll.html be an `Option<u32>` where `None` passes `-1` to act as an infinite timeout. That feels like a clearer interface than anything negative is infinity.

**Comment by sunfishcode** [comment]
Calling it 1.0 doesn't imply that there won't be a 2.0, so I think we can call it 1.0 and keep our options open for future API changes. That said, rustix is used in enough places that it's worth aiming to preserve a relatively long cadence between API breaks. My sense is that calling it 1.0 communicates that aim better, compared to calling it 39.0.

**Comment by SUPERCILEX** [comment]
Fair enough.

---

From https://github.com/bytecodealliance/rustix/pull/1105#discussion_r1718681864, let's add to the todo list that we need to fix the occurrences of `cargo clippy --workspace --all-targets --features all-apis -- -Aclippy::all -Dclippy::impl_trait_in_params`.

**Comment by SUPERCILEX** [comment]
From https://github.com/bytecodealliance/rustix/pull/1110#discussion_r1719029848:
epoll appears to be inconsistent in that it expects users to use the module prefix (i.e. `epoll::foo`) instead of using the free function directly. This is neat, but it's inconsistent with the rest of rustix's APIs: inotify, port, eventfd, io_uring, mount, shm, and probably others I didn't have time to look at. @sunfishcode thoughts on a PR that restores the `epoll_` prefix with some deprecations? We could go the other direction, but that interacts poorly with auto-complete and would be much more breaking so not worth it IMO.

Sidenote: the deprecations won't actually work due to https://github.com/rust-lang/rust/issues/30827. (For example the `fs::*mount` APIs are deprecated but there's no warning about it.)

**Comment by sunfishcode** [comment]
I've now created the [0.38 branch](https://github.com/bytecodealliance/rustix/tree/0.38) and have started doing 0.38.x releases from it, so the main branch can now start accepting semver-incompatible fixes. First up is [porting the 1.0-staging patches](https://github.com/bytecodealliance/rustix/pull/1152).

**Comment by raftario** [comment]
Is there anything you could use outside help with as part of the effort towards a 1.0 release ?

**Comment by sunfishcode** [comment]
@raftario Anyone's welcome to work on any of the items from the checklist at the top here that isn't checked and doesn't have a PR next to it. Some of them are involved, but some are just simple renames.

**Comment by sunfishcode** [comment]
Also, anything with a question mark is known to need further thought.

**Comment by sunfishcode** [comment]
All todo items here are now either fixed, have posted PRs, or are tentatively recategorized to "Defering for now". I'll give these some time, while I work on documenting the changes in CHANGELOG.md and do extra testing and tidying, but the end is now in sight.

> From [#1105 (comment)](https://github.com/bytecodealliance/rustix/pull/1105#discussion_r1718681864), let's add to the todo list that we need to fix the occurrences of `cargo clippy --workspace --all-targets --features all-apis -- -Aclippy::all -Dclippy::impl_trait_in_params` (and `use-libc`).

A PR doing this for all public APIs is posted at https://github.com/bytecodealliance/rustix/pull/1283.

> From [#1110 (comment)](https://github.com/bytecodealliance/rustix/pull/1110#discussion_r1719029848): epoll appears to be inconsistent in that it expects users to use the module prefix (i.e. `epoll::foo`) instead of using the free function directly. This is neat, but it's inconsistent with the rest of rustix's APIs: inotify, port, eventfd, io_uring, mount, shm, and probably others I didn't have time to look at. [@sunfishcode](https://github.com/sunfishcode) thoughts on a PR that restores the `epoll_` prefix with some deprecations? We could go the other direction, but that interacts poorly with auto-complete and would be much more breaking so not worth it IMO.

In my experience the autocomplete is ok once one has the appropriate `use` of the API module in scope.

I've now filed https://github.com/bytecodealliance/rustix/pull/1284  to use this style in the port API, and I've ensured that all modules using this style have examples showing the appropriate `use`, and doc aliases.

eventfd is just one function and one type so I don't think it needs a `pub mod`. That leaves io_uring and mount, which are a little harder to fit into this style. `mount::un` feels weird, `IoringSendFlags` would clash with `SendFlags` without its prefix, and subjectively they don't seem to fit this style quite as well.

> I'd like to propose making the `timeout` param in https://docs.rs/rustix/latest/rustix/event/fn.poll.html be an `Option<u32>` where `None` passes `-1` to act as an infinite timeout. That feels like a clearer interface than anything negative is infinity.

I haven't yet made this change. I do like how it makes the interface clearer, but I'm unsure about the range check it introduces.

> If this is going to be a stable release, we should make sure that `libc` and `linux-raw-sys` aren't exposed in the public API. I know there are still a few places where it is.

With https://github.com/bytecodealliance/rustix/pull/1152 now landed, https://github.com/bytecodealliance/rustix/pull/1277 and https://github.com/bytecodealliance/rustix/pull/1282 remove the last linux-raw-sys types from the public API.

I haven't yet removed all the libc types when using the libc backend. That would require duplicating a lot of platform-specific types like `stat` which gratuitously varies in all kinds of details across architectures and OS's. Perhaps just avoiding linux-raw-sys is good enough for now, because the libc crate doesn't have semver changes nearly as often.

None of this is final at this point; I'm open to feedback here.

**Comment by SUPERCILEX** [comment]
> I haven't yet made this change. I do like how it makes the interface clearer, but I'm unsure about the range check it introduces.

By this do you mean that we're limiting possible inputs the caller can supply (namely no negative numbers). I feel like that's reasonable as we probably want a different API if negative numbers start meaning something else.

---

I'd really like to see the story around MaybeUninit buffers resolved for 1.0 (or a clear expectation that there will be a 2.0 addressing the issue). I'm still on team dependent types (as in the input to the function determines the return type), but I'm not sure how we should hash this out.

**Comment by sunfishcode** [comment]
> > I haven't yet made this change. I do like how it makes the interface clearer, but I'm unsure about the range check it introduces.
> 
> By this do you mean that we're limiting possible inputs the caller can supply (namely no negative numbers). I feel like that's reasonable as we probably want a different API if negative numbers start meaning something else.

If it's `Option<u32>`, then the `u32`'s range includes values greater than `poll`'s `c_int` supports. Maybe it means we should just go all the way to `Option<Timespec>` and use `ppoll` in the implementation when we can (Linux, most BSDs).

> I'd really like to see the story around MaybeUninit buffers resolved for 1.0 (or a clear expectation that there will be a 2.0 addressing the issue). I'm still on team dependent types (as in the input to the function determines the return type), but I'm not sure how we should hash this out.

Is that https://github.com/bytecodealliance/rustix/pull/1108 and https://github.com/bytecodealliance/rustix/pull/1110? Thanks for the remainder; I'll take another look at those before the release.

**Comment by SUPERCILEX** [comment]
> we should just go all the way to Option<Timespec> and use ppoll

If we can, that sounds even better!

---

Yup, mostly #1110 as I think it could have ripple effects (e.g. getting rid of `io::read_uninit`).

**Comment by sunfishcode** [comment]
> > we should just go all the way to Option and use ppoll
> 
> If we can, that sounds even better!

I've now filed https://github.com/bytecodealliance/rustix/pull/1285 to do that.

> Yup, mostly [#1110](https://github.com/bytecodealliance/rustix/pull/1110) as I think it could have ripple effects (e.g. getting rid of `io::read_uninit`).

I've now filed https://github.com/bytecodealliance/rustix/pull/1290 starting to prototype something.

**Comment by sunfishcode** [comment]
I've now published rustix 1.0.0-prerelease.0. For anyone following this issue, please test it out and report any findings!

I've documented all the API changes I'm aware of [here](https://github.com/bytecodealliance/rustix/blob/main/CHANGES.md); please let me know if anything there is unclear or if there's something not covered.

A potential change that hasn't landed yet is #1290. It's mostly a backwards-compatible change, however it is technically an API break because in some cases it requires users add a `&mut *`. If that change lands, I'll plan to do another prerelease before the final release.

**Comment by sunfishcode** [comment]
My todo list now looks like:
 - [ ] #1337
 - [ ] #1348
 - [ ] #1290 
 - [ ] #1108

**Comment by SUPERCILEX** [comment]
Just did the upgrade in Ringboard and it went pretty smoothly: https://github.com/SUPERCILEX/clipboard-history/commit/28109d2641baeaeab494842cfb4f7bea2c08468c

**Comment by Stebalien** [comment]
I've tested on both tempfile and xattr and I've seen no real issues.

**Comment by sunfishcode** [comment]
Thanks for the reports! I've now done more testing too, and fixed a few issues that came up. I think everything is ready for a 1.0.0 release. I'm thinking of doing the release two days from now, unless any problems surface.

**Comment by sunfishcode** [comment]
[Rustix 1.0.0](https://crates.io/crates/rustix/1.0.0) is now released! Thanks to everyone who helped submit patches, bug reports, code reviews, and testing!
